const express = require('express')
const operationController = require('./../controllers/operationController')
const clientController = require('./../controllers/clientController')
const reportController = require('./../controllers/reportController')
const registerController = require('./../controllers/registerController')
const invoiceController = require('./../controllers/invoiceController')
const stokeController = require('./../controllers/stokeController')
const router = express.Router()

router.get('/getOrdes/:id', clientController.getOrdes)
router.get('/getOldOrdes/:id', clientController.getOldestOrdes)
router.get('/getService', operationController.getServices)
router.get('/getService/:id', clientController.getMyServices)
router.get('/getOrdems', operationController.getOrdems)
router.get('/verifyClient/:id', clientController.verifyClient)
router.get('/getClients', clientController.getClients)
router.get('/getInvoice', invoiceController.getInvoice)
router.get('/getStoke', stokeController.getStoke)
router.get('/getClientInvoices/:id', invoiceController.getClientInvoices)

router.post('/getReport', reportController.report)
router.post('/getInvoiceReport', reportController.invoiceReport)
router.post('/facture', reportController.factura)
router.post('/quotFacture', reportController.quotFactura)
router.post('/generalFat', reportController.generalFat)
router.post('/quoteFat', reportController.quoteFat)
router.post('/factureDocx', operationController.getDocx)
router.post('/balance', reportController.balance)
router.post('/createService', operationController.addService)
router.post('/ordeService', operationController.ordeService)
router.post('/createClient', clientController.addClient)
router.post('/saveInvoice', invoiceController.saveInvoice)
router.post('/printInvoice', invoiceController.printInvoice)
router.post('/ordemRegister', registerController.ordemRegister)
router.post('/getOrdes', operationController.getOrdesByConditions)
router.post('/rangeDate', reportController.rangeReport)
router.post('/anyReport', reportController.anyReport)
router.post('/updateStoke', stokeController.updateStoke) 

router.patch('/endOrdem/:id', operationController.endOrdem)
router.patch('/updateClient/:id', clientController.updateClient)
router.patch('/updateQty/:id', stokeController.updateQty)
router.patch('/updateInvoiceStatus/:id', invoiceController.updateInvoiceStatus)

router.delete('/deleteClient/:id', clientController.deleteClient)
router.delete('/removeService/:id', operationController.removeService)
router.delete('/removeOrdem/:id', operationController.removeOrdem)

module.exports = router